from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BlacklistSource:
    name: str
    zone: str
    lookup: str
    weight: int
    category: str
    priority: str


def _ip(name: str, zone: str, weight: int = 3, category: str = "dnsbl", priority: str = "P1") -> BlacklistSource:
    return BlacklistSource(name=name, zone=zone, lookup="ip", weight=weight, category=category, priority=priority)


def _domain(
    name: str,
    zone: str,
    weight: int = 4,
    category: str = "domain",
    priority: str = "P2",
) -> BlacklistSource:
    return BlacklistSource(name=name, zone=zone, lookup="domain", weight=weight, category=category, priority=priority)


DNSBL_SOURCES: list[BlacklistSource] = [
    _ip("Spamhaus ZEN", "zen.spamhaus.org", 15, priority="P0"),
    _domain("Spamhaus DBL", "dbl.spamhaus.org", 15, priority="P0"),
    _ip("Barracuda BRBL", "b.barracudacentral.org", 15, priority="P0"),
    _ip("SORBS Combined", "dnsbl.sorbs.net", 15, priority="P0"),
    _ip("SpamCop SCBL", "bl.spamcop.net", 5, priority="P0"),
    _ip("CBL", "cbl.abuseat.org", 5, priority="P0"),
    _ip("PSBL", "psbl.surriel.com", 4, priority="P1"),
    _ip("Invaluement ivmSIP", "dnsbl.invaluement.com", 5, priority="P1"),
    _domain("Invaluement ivmURI", "uribl.invaluement.com", 5, category="uribl", priority="P1"),
    _ip("UCEPROTECT Level 1", "dnsbl-1.uceprotect.net", 4, priority="P1"),
    _ip("UCEPROTECT Level 2", "dnsbl-2.uceprotect.net", 4, priority="P1"),
    _ip("UCEPROTECT Level 3", "dnsbl-3.uceprotect.net", 4, priority="P1"),
    _ip("Truncate", "truncate.gbudb.net", 4, priority="P1"),
    _ip("JustSpam", "dnsbl.justspam.org", 4, priority="P1"),
    _domain("SURBL Multi", "multi.surbl.org", 5, category="surbl", priority="P2"),
    _domain("URIBL Black", "black.uribl.com", 5, category="uribl", priority="P2"),
    _domain("URIBL Grey", "grey.uribl.com", 4, category="uribl", priority="P2"),
    _domain("URIBL Red", "red.uribl.com", 4, category="uribl", priority="P2"),
    _domain("URIBL Multi", "multi.uribl.com", 5, category="uribl", priority="P2"),
    _ip("0SPAM", "0spam.fusionzero.com", 3),
    _ip("0SPAM RBL", "rbl.0spam.org", 3),
    _ip("Access Redhawk", "access.redhawk.org", 3),
    _ip("All SORBS", "all.sorbs.net", 4),
    _ip("aspews.ext", "aspews.ext.sorbs.net", 3),
    _ip("Backscatterer", "ips.backscatterer.org", 4),
    _ip("Badconf", "badconf.rhsbl.sorbs.net", 3),
    _ip("Blocklist.de", "bl.blocklist.de", 4),
    _ip("Bogons", "bogons.cymru.com", 3),
    _ip("Cart00ney", "dnsbl.cart00ney.net", 3),
    _ip("Cyberlogic", "blacklist.cyberlogic.net", 3),
    _ip("DroneBL", "dnsbl.dronebl.org", 4),
    _ip("dnsbl.kempt", "dnsbl.kempt.net", 3),
    _ip("dnsbl.tornevall", "dnsbl.tornevall.org", 3),
    _ip("dnsrbl.swinog", "dnsrbl.swinog.ch", 3),
    _ip("DRMX", "drmx.org", 3),
    _ip("DSBL", "list.dsbl.org", 3),
    _ip("Dynablock", "dynablock.njabl.org", 3),
    _ip("Fabelsources", "dnsbl.fabel.dk", 3),
    _ip("Hostkarma Black", "blacklist.hostkarma.com", 4),
    _ip("Hostkarma Brown", "brownlist.hostkarma.com", 4),
    _ip("Hostkarma White", "whitelist.hostkarma.com", 3),
    _ip("Interserver", "rbl.interserver.net", 4),
    _ip("JIPPG", "ips.dnsbl.sorbs.net", 3),
    _ip("Lashback UBL", "ubl.unsubscore.com", 4),
    _ip("Mailspike Black", "bl.mailspike.net", 4),
    _ip("Mailspike Z", "z.mailspike.net", 4),
    _ip("MSRBL", "spamrbl.imp.ch", 3),
    _ip("NoSolicitado", "bl.nosolicitado.org", 3),
    _ip("Nordspam", "dbl.nordspam.com", 3),
    _ip("OpenBL", "blacklist.woody.ch", 3),
    _ip("ORVEDB", "relays.orvedb.aupads.org", 3),
    _ip("Passive Spam", "bl.score.senderscore.com", 4),
    _ip("Probes", "problems.dnsbl.sorbs.net", 3),
    _ip("Proxy BL", "proxy.bl.gweep.ca", 3),
    _ip("RBL JP", "rbl.jp", 3),
    _ip("RATS Dyna", "dyna.spamrats.com", 4),
    _ip("RATS NoPtr", "noptr.spamrats.com", 4),
    _ip("RATS Spam", "spam.spamrats.com", 4),
    _ip("SEM Backscatter", "backscatter.spameatingmonkey.net", 3),
    _ip("SEM Bad Reputation", "bad-reputation.spameatingmonkey.net", 4),
    _ip("SEM Fresh", "fresh.spameatingmonkey.net", 3),
    _ip("SenderScore", "bl.score.senderscore.com", 4),
    _ip("SORBS Badconf", "badconf.rhsbl.sorbs.net", 3),
    _ip("SORBS DUHL", "dul.dnsbl.sorbs.net", 4),
    _ip("SORBS HTTP", "http.dnsbl.sorbs.net", 3),
    _ip("SORBS Misc", "misc.dnsbl.sorbs.net", 3),
    _ip("SORBS New", "new.dnsbl.sorbs.net", 3),
    _ip("SORBS Nomail", "nomail.rhsbl.sorbs.net", 3),
    _ip("SORBS Recent", "recent.dnsbl.sorbs.net", 3),
    _ip("SORBS SMTP", "smtp.dnsbl.sorbs.net", 4),
    _ip("SORBS SOCKS", "socks.dnsbl.sorbs.net", 4),
    _ip("SORBS Spam", "spam.dnsbl.sorbs.net", 4),
    _ip("SORBS Web", "web.dnsbl.sorbs.net", 3),
    _ip("SpamRBL", "spamrbl.imp.ch", 3),
    _ip("Spamrats All", "all.spamrats.com", 4),
    _ip("Spamhaus CSS", "css.spamhaus.org", 5),
    _ip("Spamhaus PBL", "pbl.spamhaus.org", 4),
    _ip("Spamhaus XBL", "xbl.spamhaus.org", 5),
    _ip("Spamhaus SBL", "sbl.spamhaus.org", 5),
    _ip("SWINOG", "dnsrbl.swinog.ch", 3),
    _ip("Tor Exit", "tor.dan.me.uk", 3),
    _ip("TRIUMF", "rbl.triumf.ca", 3),
    _ip("Weighted Private", "bl.nszones.com", 3),
    _ip("WPBL", "db.wpbl.info", 4),
    _ip("ZapBL", "dnsbl.zapbl.net", 4),
    _domain("Abusix Mail Intelligence", "combined.mail.abusix.zone", 4, category="uribl"),
    _domain("Abusix URI", "uri.abusix.zone", 4, category="uribl"),
    _domain("DBL Alternate", "dbl.nordspam.com", 4, category="uribl"),
    _domain("Fresh15", "fresh15.spameatingmonkey.net", 3, category="uribl"),
    _domain("HSBL", "hsbl.habeas.com", 3, category="uribl"),
    _domain("Karma Blacklist", "karmablacklist.org", 3, category="uribl"),
    _domain("RHSBL Abuse", "abuse.rhsbl.sorbs.net", 3, category="rhsbl"),
    _domain("RHSBL Malware", "malware.rhsbl.sorbs.net", 4, category="rhsbl"),
    _domain("RHSBL Nomail", "nomail.rhsbl.sorbs.net", 3, category="rhsbl"),
    _domain("RHSBL Phishing", "phishing.rhsbl.sorbs.net", 4, category="rhsbl"),
    _domain("RHSBL Redirector", "redirector.rhsbl.sorbs.net", 3, category="rhsbl"),
    _domain("RHSBL SPAM", "spam.rhsbl.sorbs.net", 4, category="rhsbl"),
    _domain("RHSBL URL", "rhsbl.sorbs.net", 4, category="rhsbl"),
    _domain("SEM URI", "uribl.spameatingmonkey.net", 4, category="uribl"),
    _domain("Spam404", "db.spam404.net", 4, category="uribl"),
    _domain("SURBL Abuse", "abuse.rbl.surbl.org", 4, category="surbl"),
    _domain("SURBL CR", "cr.rbl.surbl.org", 4, category="surbl"),
    _domain("SURBL JP", "jp.rbl.surbl.org", 3, category="surbl"),
    _domain("SURBL MW", "mw.surbl.org", 4, category="surbl"),
    _domain("SURBL PH", "ph.surbl.org", 4, category="surbl"),
    _domain("SURBL WS", "ws.surbl.org", 4, category="surbl"),
    _domain("URIBL Greylist", "grey.uribl.com", 4, category="uribl"),
    _domain("URIBL Blacklist", "black.uribl.com", 5, category="uribl"),
    _domain("URIBL Redlist", "red.uribl.com", 4, category="uribl"),
    _domain("URIBL Multi-Surbl", "multi.uribl.com", 5, category="uribl"),
]
